services:
  - type: web
    name: rfinance-api
    runtime: node
    plan: free
    region: ohio
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start:prod
    healthCheckPath: /v1
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://www.rfinanece-vercel.app,https://rfinanece-web-git-main-nikollas-projects-9321ac0f.vercel.app,https://rfinanece-g2pe0tq1p-nikollas-projects-9321ac0f.vercel.app
